import type { Metadata } from "next";
import { LegalPage, LegalSection } from "@/components/kairo/LegalPage";

export const metadata: Metadata = { title: "Terms · Aether" };

// TODO(before launch): set this to your real support address.
const CONTACT = "hello@aether.app";

export default function TermsPage() {
  return (
    <LegalPage title="Terms of Service" updated="July 2026">
      <p>
        These terms cover your use of Aether. By creating an account or using the app, you agree to them. If you
        don&rsquo;t agree, please don&rsquo;t use the service.
      </p>

      <LegalSection heading="The service">
        <p>
          Aether turns goals into plans and helps you decide what to do next. Features may change as we improve the
          product.
        </p>
      </LegalSection>

      <LegalSection heading="Your account">
        <p>
          You&rsquo;re responsible for keeping your account secure and for the content you create. Don&rsquo;t use Aether
          for anything unlawful, or to disrupt, abuse, or overload the service.
        </p>
      </LegalSection>

      <LegalSection heading="AI-generated plans">
        <p>
          Plans, breakdowns, and answers are generated by AI and are suggestions to help you act — not professional,
          legal, medical, or financial advice. Use your own judgment, and verify anything important.
        </p>
      </LegalSection>

      <LegalSection heading="Availability and warranty">
        <p>
          The service is provided &ldquo;as is,&rdquo; without warranties of any kind. We work to keep Aether reliable but
          can&rsquo;t guarantee it will be uninterrupted or error-free.
        </p>
      </LegalSection>

      <LegalSection heading="Limitation of liability">
        <p>
          To the extent permitted by law, Aether is not liable for indirect or consequential damages arising from your
          use of the service.
        </p>
      </LegalSection>

      <LegalSection heading="Ending your use">
        <p>
          You can delete your account at any time from Settings. We may suspend accounts that violate these terms.
        </p>
      </LegalSection>

      <LegalSection heading="Changes and contact">
        <p>
          We may update these terms; we&rsquo;ll revise the date above when we do. Questions? Email{" "}
          <a href={`mailto:${CONTACT}`} className="text-accent underline underline-offset-2">{CONTACT}</a>.
        </p>
      </LegalSection>
    </LegalPage>
  );
}
